language: python
python:
  - "2.7"
# Install C libraries
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - gfortran
      - libopenblas-dev
      - liblapack-dev
# Command to install dependencies
install: python setup.py install
# Command to run tests
script: nosetests
